/* Darts module: immutable SQLite input, addressed read-only reconstruction.
 * SQLite file format: https://www.sqlite.org/fileformat2.html
 * This reader admits ordinary rowid tables only; unsupported carriers stay unresolved.
 */
(function(root){
'use strict';
const version='1.0.0',defaultIdentity='60c418899d9a0c8adee4d5b628a5f0ec0c4ac13a9259ca31fe30212fcc589bf4';
function open(input){
 const bytes=input instanceof Uint8Array?input:new Uint8Array(input),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);
 const fail=message=>{throw Error('Darts module: '+message);},check=(offset,length)=>{if(!Number.isSafeInteger(offset)||offset<0||length<0||offset+length>bytes.length)fail('source boundary exceeded');};
 check(0,100);if(new TextDecoder().decode(bytes.subarray(0,16))!=='SQLite format 3\0')fail('unsupported source header');
 const u16=o=>{check(o,2);return view.getUint16(o);},u32=o=>{check(o,4);return view.getUint32(o);},pageSize=u16(16)===1?65536:u16(16),usable=pageSize-bytes[20];
 if(pageSize<512||pageSize>65536||(pageSize&(pageSize-1))||bytes.length%pageSize||usable<480)fail('invalid page boundary');
 if(bytes[18]>2||bytes[19]>2)fail('unsupported database version');
 const encoding=u32(56),decoder=new TextDecoder(encoding===1?'utf-8':encoding===2?'utf-16le':encoding===3?'utf-16be':'utf-8',{fatal:true});if(![1,2,3].includes(encoding))fail('unsupported text encoding');
 const integer=n=>{if(n>BigInt(Number.MAX_SAFE_INTEGER)||n<BigInt(Number.MIN_SAFE_INTEGER))fail('integer exceeds supported exact range');return Number(n);};
 function varint(offset,limit=bytes.length){let n=0n;for(let i=0;i<9;i++){if(offset+i>=limit)fail('incomplete varint');const b=bytes[offset+i];if(i===8)return {value:(n<<8n)|BigInt(b),next:offset+9};n=(n<<7n)|BigInt(b&127);if(!(b&128))return {value:n,next:offset+i+1};}fail('invalid varint');}
 function record(payload){const v=new DataView(payload.buffer,payload.byteOffset,payload.byteLength),read=offset=>{let n=0n;for(let i=0;i<9;i++){if(offset+i>=payload.length)fail('incomplete record header');const b=payload[offset+i];if(i===8)return{value:(n<<8n)|BigInt(b),next:offset+9};n=(n<<7n)|BigInt(b&127);if(!(b&128))return{value:n,next:offset+i+1};}};const head=read(0),end=integer(head.value);if(end>payload.length||end<head.next)fail('invalid record header');let at=head.next,pos=end;const values=[];
  while(at<end){const serial=read(at);at=serial.next;const type=integer(serial.value),length=type===0||type===8||type===9?0:type===1?1:type===2?2:type===3?3:type===4?4:type===5?6:type===6||type===7?8:type>=12?Math.floor((type-12)/2):-1;if(length<0||pos+length>payload.length)fail('unsupported or incomplete record');let value;
   switch(type){case 0:value=null;break;case 8:value=0;break;case 9:value=1;break;case 7:value=v.getFloat64(pos);break;default:if(type>=12)value=type%2?decoder.decode(payload.subarray(pos,pos+length)):payload.slice(pos,pos+length);else{let n=0n;for(let i=0;i<length;i++)n=(n<<8n)|BigInt(payload[pos+i]);if(payload[pos]&128)n-=1n<<BigInt(length*8);value=integer(n);}}
   values.push(value);pos+=length;
  }if(at!==end||pos!==payload.length)fail('record extent mismatch');return values;
 }
 function rows(rootPage){const result=[],visited=new Set();function walk(number){if(!number||number>bytes.length/pageSize||visited.has(number))fail('invalid or circular table page');visited.add(number);const base=(number-1)*pageSize,start=base+(number===1?100:0),kind=bytes[start],count=u16(start+3);if(![5,13].includes(kind))fail('unsupported non-rowid table page');const header=kind===5?12:8;check(start+header,count*2);
   for(let i=0;i<count;i++){let pos=base+u16(start+header+i*2);if(pos<start+header+count*2||pos>=base+usable)fail('invalid cell offset');if(kind===5){const child=u32(pos);walk(child);continue;}const p=varint(pos,base+usable),size=integer(p.value),r=varint(p.next,base+usable),rowid=integer(BigInt.asIntN(64,r.value));pos=r.next;if(size<0||size>bytes.length)fail('invalid payload length');const maxLocal=usable-35,minLocal=Math.floor((usable-12)*32/255)-23,extra=minLocal+(size-minLocal)%(usable-4),local=size<=maxLocal?size:extra<=maxLocal?extra:minLocal;check(pos,local);if(pos+local>base+usable)fail('local payload crosses page');const payload=new Uint8Array(size);payload.set(bytes.subarray(pos,pos+local));let copied=local,overflow=size>local?u32(pos+local):0;const overflowSeen=new Set();while(copied<size){if(!overflow||overflow>bytes.length/pageSize||overflowSeen.has(overflow))fail('missing or circular overflow page');overflowSeen.add(overflow);const b=(overflow-1)*pageSize,n=Math.min(size-copied,usable-4);payload.set(bytes.subarray(b+4,b+4+n),copied);copied+=n;overflow=u32(b);}result.push({rowid,values:record(payload)});
   }if(kind===5)walk(u32(start+8));}walk(rootPage);return result;}
 const schema=rows(1).map(r=>Object.fromEntries(['type','name','tbl_name','rootpage','sql'].map((key,i)=>[key,r.values[i]]))),cache=new Map();
 function columns(sql){const begin=sql.indexOf('('),end=sql.lastIndexOf(')');if(begin<0||end<begin||/WITHOUT\s+ROWID/i.test(sql))fail('unsupported table schema');let depth=0,quote='',start=begin+1,parts=[];for(let i=start;i<end;i++){const c=sql[i];if(quote){if(c===quote){if(sql[i+1]===quote)i++;else quote='';}continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='['){quote=']';continue;}if(c==='(')depth++;if(c===')')depth--;if(c===','&&!depth){parts.push(sql.slice(start,i).trim());start=i+1;}}parts.push(sql.slice(start,end).trim());return parts.filter(p=>! /^(CONSTRAINT|PRIMARY\s+KEY|UNIQUE|CHECK|FOREIGN\s+KEY)\b/i.test(p)).map(p=>{const m=p.match(/^(?:"((?:[^"]|"")+)"|`([^`]+)`|\[([^\]]+)\]|([^\s]+))(?:\s+([\s\S]*))?$/);if(!m)fail('unresolved column schema');return{name:(m[1]||m[2]||m[3]||m[4]).replaceAll('""','"'),rowid:/^INTEGER\b/i.test(m[5]||'')&&/PRIMARY\s+KEY/i.test(m[5])&&!/PRIMARY\s+KEY\s+DESC/i.test(m[5])};});}
 function table(name){if(cache.has(name))return cache.get(name);const s=schema.find(s=>s.type==='table'&&s.name===name);if(!s||!s.sql)fail('table unavailable: '+name);const cols=columns(s.sql),data=rows(s.rootpage).map(r=>{if(r.values.length>cols.length)fail('column extent mismatch');return Object.fromEntries(cols.map((c,i)=>[c.name,c.rowid&&r.values[i]===null?r.rowid:r.values[i]??null]));});cache.set(name,data);return data;}
 return {version,bytes:bytes.length,pageSize,schema,table,boundary:'Immutable standalone SQLite rowid tables; no SQL execution, writes, WAL recovery, inferred fields or integer rounding'};
}
async function admit(input,source,expected){const bytes=input instanceof Uint8Array?input:new Uint8Array(input),identity=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');if(expected&&identity!==expected)throw Error('Darts module source identity changed');const reader=open(bytes),address='modules/darts/sources/'+identity;return {address,source,identity,version,reader,resolve:table=>({address:address+'/tables/'+encodeURIComponent(table),source,identity,values:reader.table(table)}),boundary:reader.boundary};}
function selection(source){const get=t=>source.reader.table(t);const players=get('player'),opponents=get('opponent'),team=get('team'),participation=get('match_opponent');
const strip=r=>{const {stats,...rest}=r;return {...rest,opaque_stats_address:stats?'statistics payload retained in fresh-tablet.sqlite':null};};
const games=get('match').map(m=>{const sides=participation.filter(p=>p.match_id===m._id).sort((a,b)=>a.order_no-b.order_no).map(p=>({id:p.OPPONENT_ID,order:p.order_no,source:p._id,members:team.filter(t=>t.opponent_id===p.OPPONENT_ID).map(t=>t.player_id)}));
const legs=[];let set=1,legInSet=1,starter=0,wins=Array(sides.length).fill(0),current=null,remaining=[],visit=0;
const initial=m.handicap?m.handicap.split(',').map(Number):[];
const open=()=>{current={number:legs.length+1,set,legInSet,starter:sides[starter]?.id,turns:[],winner:null};remaining=sides.map((_,i)=>initial[i]??m.startpoints);visit=0;legs.push(current);};
const tokens=m.scores?m.scores.split(','):[];
for(let i=0;i<tokens.length;i++){if(!sides.length)break;if(!current)open();const raw=Number(tokens[i]),sideIndex=(starter+visit)%sides.length;const checkout=raw<0,darts=checkout?(raw>=-3?-raw:Math.floor(-raw/1000)):3;const before=remaining[sideIndex];const score=checkout?before:raw;remaining[sideIndex]=checkout?0:before-score;current.turns.push({i:i+1,side:sides[sideIndex].id,raw,score,darts,before,remaining:remaining[sideIndex],checkout});visit++;if(checkout){current.winner=sides[sideIndex].id;wins[sideIndex]++;if(wins[sideIndex]>=m.legs){set++;legInSet=1;wins.fill(0);starter=(set-1)%sides.length;}else{legInSet++;starter=(set-1+legInSet-1)%sides.length;}current=null;}}
const warnings=[];if(!tokens.length)warnings.push('Missing score sequence');if(!sides.length)warnings.push('Missing participants');if(legs.at(-1)&&!legs.at(-1).winner)warnings.push('Final recorded leg unfinished');if(m.sets===0)warnings.push('Open-ended match setting');if(tokens.length&&m.sets>0&&set<=m.sets)warnings.push('Configured match finish not reached');
return {...m,sides,legsDerived:legs,warnings};});
const stats=get('statistics').map(strip),h2h=get('head_to_head').map(strip),weekly=get('X01_stats_history');
const data={players,opponents,team,games,stats,h2h,weekly,target:get('target'),bob27:get('bob27'),cricket:get('cricket_statistics'),cricketWeekly:get('cricket_stats_history')};

return data;}
function records(source){const records={},relations=[],schema=[...source.reader.schema].sort((a,b)=>(a.type<b.type?-1:a.type>b.type?1:0)||(a.name<b.name?-1:a.name>b.name?1:0));const enc=v=>v instanceof Uint8Array?{type:'sqlite-blob',base64:typeof Buffer==='object'?Buffer.from(v).toString('base64'):btoa(Array.from(v,n=>String.fromCharCode(n)).join(''))}:v;for(const table of schema.filter(s=>s.type==='table')){const rows=source.reader.table(table.name);rows.forEach((row,i)=>{const id=row._id??'row-'+(i+1),key=table.name+'/'+id;records[key]={address:key,source:{database:'../fresh-tablet.sqlite',sha256:source.identity,table:table.name,id:row._id??null,row:i+1},grain:'native database record',values:Object.fromEntries(Object.entries(row).map(([k,v])=>[k,enc(v)]))};});}
const add=(from,field,to)=>{if(!records[to])throw Error('Missing relation target '+to+' from '+from);relations.push({from,field,to});};
const byId=(t,id)=>t+'/'+id;
for(const [key,r]of Object.entries(records)){const v=r.values,t=r.source.table;if(t==='team'){add(key,'player_id',byId('player',v.player_id));add(key,'opponent_id',byId('opponent',v.opponent_id));}if(t==='match_opponent'){add(key,'match_id',byId('match',v.match_id));add(key,'OPPONENT_ID',byId('opponent',v.OPPONENT_ID));}if(['statistics','bob27','target'].includes(t))add(key,'opponent_id',byId('opponent',v.opponent_id));if(['head_to_head','cricket_statistics'].includes(t)){add(key,'winner',byId('opponent',v.winner));add(key,'loser',byId('opponent',v.loser));}if(['X01_stats_history','cricket_stats_history'].includes(t))add(key,'player (opponent identity)',byId('opponent',v.player));}

return{root:{carrier:'fresh-tablet.sqlite',sha256:source.identity,...(source.identity===defaultIdentity?{device:'4b2c78f10551768e',package:'andrewgilman.dartsscoreboard'}:{})},records,relations};}
function events(source){const selected=selection(source),d={players:selected.players.map(player=>({player})),games:selected.games,weekly:selected.weekly.map(w=>{const members=selected.team.filter(t=>t.opponent_id===w.player).map(t=>selected.players.find(p=>p._id===t.player_id));return{...w,player_or_team:selected.opponents.find(o=>o._id===w.player)?.name??'Unknown',player_ids:members.map(p=>p._id).join(';'),player_names:members.map(p=>p.name).join(';'),source:'X01_stats_history/'+w._id};})},sourceHash=source.identity;const participants=g=>[...new Set(g.sides.flatMap(s=>s.members))];const events={},ledgerById=new Map(d.players.map(p=>[p.player._id,{player:p.player,source:{database:'../../fresh-tablet.sqlite',sha256:sourceHash,record:'player/'+p.player._id},entries:[],retainedSourceSummaries:[]} ]));
const add=(key,event,ids,role)=>{events[key]=event;for(const pid of ids){const ledger=ledgerById.get(pid);if(!ledger)throw Error('Missing player '+pid);ledger.entries.push({event:'../events.json#/events/'+key,relation:role(pid),with:ids.filter(x=>x!==pid)});}};
for(const g of d.games){const ids=participants(g),match='match-'+g._id;
add(match,{kind:'match',source:{table:'match',id:g._id},time:{value:g.start_date,grain:'match start only',timezone:null,end:null,resumptions:null},ordering:{scope:'within this match',acrossMatches:'unresolved'},duration:{elapsed:null,continuousPlay:null},participants:ids,sides:g.sides,configuration:{startpoints:g.startpoints,legs:g.legs,sets:g.sets,dartboard:g.dartboard,in_type:g.in_type,rules:g.rules,handicap:g.handicap,flags:g.flags},rawScores:g.scores,rawHistory:g.history,warnings:g.warnings},ids,()=> 'participant');
for(const l of g.legsDerived){const leg=match+'-set-'+l.set+'-leg-'+l.legInSet;
add(leg,{kind:'leg',parent:match,source:{table:'match',id:g._id,field:'scores'},time:{value:null,grain:'ordered within match',order:l.number},participants:ids,set:l.set,leg:l.legInSet,starterOpponent:l.starter,winnerOpponent:l.winner,finish:l.winner?'checkout retained':'unfinished',derivation:'installed APK score replay'},ids,()=> 'participant');
for(const t of l.turns){const key=match+'-score-'+t.i,side=g.sides.find(s=>s.id===t.side);
add(key,{kind:'score',parent:leg,match,source:{table:'match',id:g._id,field:'scores',token:t.i},time:{value:null,grain:'ordered visit',order:t.i},participants:ids,actor:{opponent_id:t.side,player_ids:side.members,grain:side.members.length===1?'individual':'team',individualThrower:side.members.length===1?side.members[0]:null},score:t.score,remaining:t.remaining,darts:t.darts,checkout:t.checkout,raw:t.raw,derivation:'installed APK score replay'},ids,pid=>side.members.includes(pid)?(side.members.length===1?'scorer':'scoring team member; individual thrower unresolved'):'opposing participant');}
}}
for(const w of d.weekly){const key='source-X01_stats_history-'+w._id,ids=w.player_ids.split(';').filter(Boolean).map(Number);events[key]={kind:'source summary',source:{table:'X01_stats_history',id:w._id},time:{value:null,grain:'source record; no inferred play timestamp'},participants:ids,raw:w,matchJoin:null};for(const pid of ids)ledgerById.get(pid).retainedSourceSummaries.push({event:'../events.json#/events/'+key,relation:ids.length===1?'individual summary':'shared team summary',with:ids.filter(x=>x!==pid)});}

return{sourceDatabaseHash:sourceHash,events};}
async function symbolic(source,native,eventStore){
 const recordFile='work/darts-stats-20261006/full-export/native-record-ledger.json',eventFile='work/darts-stats-20261006/player-ledgers/events.json',states=new Map(),relations=new Map(),recordIndex=new Map(),hashes=new Map();
 const digest=text=>{if(!hashes.has(text))hashes.set(text,crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)).then(bytes=>[...new Uint8Array(bytes)].map(n=>n.toString(16).padStart(2,'0')).join('')));return hashes.get(text);},pointer=key=>key.replace(/~/g,'~0').replace(/\//g,'~1'),address='work/darts-stats-20261006/fresh-tablet.sqlite#sha256='+source.identity;
 const add=(label,metadata)=>{if(states.has(label))throw Error('Darts module conflicting endpoint: '+label);states.set(label,{label,...metadata});},link=(left,relation,right)=>{const key=JSON.stringify([left,relation,right]);if(!relations.has(key))relations.set(key,{left,relation,right});};
 add(address,{root:address,kind:'sqlite',state:'RETAINED_SOURCE',identity:'sha256:'+source.identity,source:'work/darts-stats-20261006/fresh-tablet.sqlite'});
 for(const [key,record]of Object.entries(native.records)){if(record.source.id!==null)recordIndex.set(JSON.stringify([record.source.table,record.source.id]),key);const occurrence=recordFile+'#/records/'+pointer(key);add(occurrence,{root:address,kind:'native-record',state:'SOURCE_REFERENCE',source:occurrence,nativeAddress:record.address,identity:'sha256:'+await digest(JSON.stringify(record)),sourceDatabaseHash:source.identity});link(address,'CONTAINS_NATIVE_RECORD',occurrence);for(const field of Object.keys(record.values||{})){const endpoint=occurrence+'/values/'+pointer(field);add(endpoint,{root:address,kind:'native-field',state:'SOURCE_REFERENCE',source:endpoint,valueKind:record.values[field]===null?'null':typeof record.values[field],identity:'sha256:'+await digest(JSON.stringify(record.values[field]))});link(occurrence,'HAS_NATIVE_FIELD',endpoint);}}
 for(const [key,event]of Object.entries(eventStore.events)){const occurrence=eventFile+'#/events/'+pointer(key);add(occurrence,{root:address,kind:event.kind,state:'SOURCE_REFERENCE',source:occurrence,identity:'sha256:'+await digest(JSON.stringify(event)),sourceDatabaseHash:source.identity});link(address,'CONTAINS_EVENT',occurrence);if(event.parent){if(!eventStore.events[event.parent])throw Error('Darts module parent unavailable: '+event.parent);link(occurrence,'RETAINS_PARENT',eventFile+'#/events/'+pointer(event.parent));}const record=recordIndex.get(JSON.stringify([event.source?.table,event.source?.id]));if(record)link(occurrence,'REFERENCES_NATIVE_RECORD',recordFile+'#/records/'+pointer(record));}
 const nodes=new Map(),put=label=>{if(!nodes.has(label))nodes.set(label,{address:label});};for(const relation of relations.values()){put(relation.left);put(relation.right);}for(const state of states.values()){put(state.label);Object.assign(nodes.get(state.label),Object.fromEntries(Object.entries(state).filter(([key])=>key!=='label')));}put(address);
 return{schema:'notodus-ledger-projection/1',sourceAddress:source.address+'/symbolic',sourceFile:source.source,sourceSha256:source.identity,sourceModule:source.address,root:address,selectedAddress:address,firstNotodusAddress:null,nodes:[...nodes.values()],edges:[...relations.values()],layoutBoundary:'Original native symbolic relation reconstruction in memory from immutable Darts module; no expanded ledger carrier written or shipped'};
}
function preview(source,view){const d=selection(source);const fields=['matches_played','matches_won','matches_drawn','legs_played','legs_won','legs_won_darts_per_leg','points_scored','points_co','darts_thrown','winning_darts_thrown','checkout_attempts','checkouts_made','points_scored_non_os','darts_thrown_non_os','turns','turns_non_os','range4'];
const ratio=(x,n)=>n?x/n:null;
const players=d.players.flatMap(p=>['individual','team'].map(mode=>{
const own=new Set(d.team.filter(t=>t.player_id===p._id&&(mode==='individual'?d.team.filter(x=>x.opponent_id===t.opponent_id).length===1:d.team.filter(x=>x.opponent_id===t.opponent_id).length>1)).map(t=>t.opponent_id));
const stats=d.stats.filter(s=>own.has(s.opponent_id)&&s.start_points>0);
const formats=[...new Set(stats.map(s=>s.start_points))].map(points=>{
const a=stats.filter(s=>s.start_points===points),totals=Object.fromEntries(fields.map(k=>[k,a.reduce((n,s)=>n+s[k],0)]));
for(const k of ['best_checkout','best_score','winning_darts_per_leg_max']){const vals=a.map(s=>s[k]).filter(n=>n>=0);totals[k]=vals.length?Math.max(...vals):null;}
const mins=a.map(s=>s.winning_darts_per_leg_min).filter(n=>n>=0);totals.winning_darts_per_leg_min=mins.length?Math.min(...mins):null;
const history=d.games.filter(g=>g.startpoints===points&&g.sides.some(s=>own.has(s.id))).sort((a,b)=>a.start_date.localeCompare(b.start_date)).map(g=>{const sides=new Set(g.sides.filter(s=>own.has(s.id)).map(s=>s.id));const legs=g.legsDerived.filter(l=>l.turns.some(t=>sides.has(t.side))),turns=legs.flatMap(l=>l.turns.filter(t=>sides.has(t.side))),wins=legs.filter(l=>sides.has(l.winner)),winDarts=wins.map(l=>l.turns.filter(t=>sides.has(t.side)).reduce((n,t)=>n+t.darts,0));const co=turns.filter(t=>t.checkout),first=legs.flatMap(l=>l.turns.filter(t=>sides.has(t.side)).slice(0,3));return {id:g._id,date:g.start_date,address:'match/'+g._id,average:ratio(turns.reduce((n,t)=>n+t.score,0)*3,turns.reduce((n,t)=>n+t.darts,0)),first9:ratio(first.reduce((n,t)=>n+t.score,0)*3,first.reduce((n,t)=>n+t.darts,0)),best:turns.length?Math.max(...turns.map(t=>t.score)):null,checkout:co.length?Math.max(...co.map(t=>t.score)):null,finish:ratio(co.reduce((n,t)=>n+t.score,0),co.length),legs:legs.length,legWin:ratio(wins.length*100,legs.length),winningDarts:ratio(winDarts.reduce((n,t)=>n+t,0),winDarts.length),minimum:winDarts.length?Math.min(...winDarts):null,maximum:winDarts.length?Math.max(...winDarts):null,incomplete:!!g.warnings.length};});
const weeklyCheckout=d.weekly.filter(r=>own.has(r.player)&&r.start_points===points&&r.checkout_attempts>0).map(r=>({address:'X01_stats_history/'+r._id,date:String(r.year).padStart(4,'0')+'/W'+String(r.week).padStart(2,'0')+'/'+String(r._id).padStart(6,'0'),checkoutRate:100*r.checkouts_hit/r.checkout_attempts,checkoutHits:r.checkouts_hit,checkoutAttempts:r.checkout_attempts,year:r.year,week:r.week,opponent:r.player,rules:r.rules,inType:r.in_type,practice:r.practice,sourceDatabaseHash:source.identity}));return {points,count:totals.matches_played,stats:totals,history,weeklyCheckout,source:a.map(s=>'statistics/'+s._id),address:'players/'+(mode==='individual'?p._id:p._id+'/team')+'/formats/'+points};
}).sort((a,b)=>b.count-a.count||a.points-b.points);
return {id:mode==='individual'?p._id:p._id+'/team',mode,name:p.name+(mode==='team'?' — team games':''),count:formats.reduce((n,f)=>n+f.count,0),formats,address:'players/'+(mode==='individual'?p._id:p._id+'/team')};})).filter(p=>p.mode==='individual'||p.count>0);
const registry={};for(const p of players){registry[p.address]=p;for(const f of p.formats)registry[f.address]=f;}
const games=d.games.map(g=>({id:g._id,date:g.start_date,points:g.startpoints,warnings:g.warnings,sides:g.sides.map(s=>({...s,name:d.opponents.find(o=>o._id===s.id)?.name??String(s.id)})),legs:g.legsDerived.map(l=>({set:l.set,number:l.legInSet,winner:l.winner,turns:l.turns.map(t=>[t.i,t.side,t.score,t.darts,t.before,t.remaining,t.checkout])}))}));
const pairFields=[...fields,'best_checkout','best_score','winning_darts_per_leg_min','winning_darts_per_leg_max'];
const h2h=d.h2h.filter(s=>s.start_points>0).map(s=>[s._id,s.winner,s.loser,s.start_points,...pairFields.map(k=>s[k])]);
const teams=d.opponents.map(o=>({id:o._id,members:d.team.filter(t=>t.opponent_id===o._id).map(t=>t.player_id)}));
const state={...view,players,registry,games,h2h,pairFields,teams,producedFrom:source.address,sourceDatabase: 'fresh-tablet.sqlite'};

return state;}
function contributions(source,playerIds){const selected=playerIds==null?null:new Set(playerIds.map(String)),teams=source.reader.table('team'),groups=[],shared=[];for(const row of source.reader.table('statistics')){if(!(row.start_points>0))continue;const members=[...new Set(teams.filter(t=>t.opponent_id===row.opponent_id).map(t=>String(t.player_id)))];if(selected&&!members.some(id=>selected.has(id)))continue;const group={address:source.address+'/tables/statistics/'+row._id+'/counted-dart-grains',source:source.address+'/tables/statistics/'+row._id,opponent:row.opponent_id,members,count:row.darts_thrown,range:[0,row.darts_thrown],grain:'Counted native darts; individual unrecorded outcomes are not inferred'};if(!Number.isSafeInteger(group.count)||group.count<0)throw Error('Darts material count unresolved');if(selected&&members.length>1&&!members.every(id=>selected.has(id))){shared.push(group);continue;}groups.push(group);}return{address:source.address+'/reports/'+(selected?[...selected].sort().join(','):'whole')+'/dart-material',source:source.address,members:selected?[...selected]:null,groups,unallocatedShared:shared,count:groups.reduce((n,g)=>n+g.count,0),boundary:'Each native statistics scope counted once; complete shared scopes admitted only when all members belong to the report. Individual missing throw details remain unresolved'};}
const api={version,defaultIdentity,open,admit,selection,records,events,symbolic,preview,contributions};if(typeof module==='object')module.exports=api;else{
 root.dartDartsModule=api;
 const cache=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('dart-darts-modules',1);request.onupgradeneeded=()=>request.result.createObjectStore('modules',{keyPath:'address'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
 async function selected(){let db;try{db=await cache();return await new Promise((resolve,reject)=>{const request=db.transaction('modules').objectStore('modules').get('modules/darts/selected');request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);});}catch{return null;}finally{db?.close();}}
 api.ready=(async()=>{const retained=await selected();let source;if(retained?.bytes)source=await admit(retained.bytes,retained.source,retained.identity);else{const response=await fetch('./fresh-tablet.sqlite',{cache:'no-store'});if(!response.ok)throw Error('Default Darts module unavailable: '+response.status);source=await admit(await response.arrayBuffer(),'./fresh-tablet.sqlite',defaultIdentity);}api.source=source;document.body.dataset.dartsModuleSource=source.address;document.body.dataset.dartsModuleVersion=version;return source;})();api.ready.catch(error=>document.body.dataset.dartsModuleDifference=error.message);
 api.select=async file=>{const bytes=new Uint8Array(await file.arrayBuffer()),source=await admit(bytes,'browser/upload/'+encodeURIComponent(file.name));selection(source);records(source);const prior=await selected(),state={address:source.address+'/selection/'+crypto.randomUUID(),was:prior?.state||api.source?.address||null,source:source.source,identity:source.identity,bytes,version},db=await cache();try{await new Promise((resolve,reject)=>{const transaction=db.transaction('modules','readwrite'),store=transaction.objectStore('modules');store.add(state);store.put({...state,address:'modules/darts/selected',state:state.address});transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error||Error('Darts selection was not retained'));});}finally{db.close();}return{address:state.address,source:source.address,bytes:bytes.length,boundary:'Verified compatible immutable module selected for the next page reconstruction; game and score ledgers unchanged'};};
 api.useDefault=async()=>{const db=await cache();try{await new Promise((resolve,reject)=>{const transaction=db.transaction('modules','readwrite');transaction.objectStore('modules').put({address:'modules/darts/selected',state:'modules/darts/default',was:api.source?.address||null,source:'./fresh-tablet.sqlite',identity:defaultIdentity});transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error);});}finally{db.close();}};
 function controls(){const owner=document.querySelector('#player-filter-preview [data-shell-display]');if(!owner||owner.querySelector('[data-darts-module-controls]'))return false;const frame=document.createElement('section');frame.dataset.dartsModuleControls='';frame.dataset.stateAddress='modules/darts/controls';const label=document.createElement('label'),input=document.createElement('input'),status=document.createElement('p'),reset=document.createElement('button');label.textContent='Darts module';input.type='file';input.accept='.sqlite,.db,application/vnd.sqlite3';input.setAttribute('aria-label','Read another Darts ledger');reset.type='button';reset.textContent='Use original Darts module';status.textContent='Original compact ledger is the default. Upload a compatible ledger to select its own addressed source.';label.append(input);frame.append(label,status,reset);owner.append(frame);input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{input.disabled=true;status.textContent='Reading selected source';const receipt=await api.select(file);status.textContent='Selected '+receipt.bytes+' byte Darts module';location.reload();}catch(error){status.textContent=error.message;input.disabled=false;}};reset.onclick=async()=>{try{await api.useDefault();location.reload();}catch(error){status.textContent=error.message;}};return true;}
 const observer=new MutationObserver(()=>{if(controls())observer.disconnect();});observer.observe(document.documentElement,{childList:true,subtree:true});controls();
}
})(typeof window==='object'?window:globalThis);
